### ISSUE TITLE
Problem with F atoms in NMR analysis

### ISSUE THREAD

**Issue by jvalegre** [ekwan/Jprogdyn#1]
Dear Eugene,

We're trying to calculate NMR corrections for different molecules that contain halogen atoms but we get the following error (it happens for F and Br): 

***
=== NMR Raw Correction Analysis ===

[WARNING] 
java.lang.IllegalArgumentException: element not found for symbol Br
    at edu.harvard.chemistry.ekwan.Jprogdyn.Element.getElement (Element.java:54)
    at edu.harvard.chemistry.ekwan.Jprogdyn.NMRTrajectoryAnalyzer.analyze (NMRTrajectoryAnalyzer.java:136)
    at edu.harvard.chemistry.ekwan.Jprogdyn.Loader.main (Loader.java:704)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:282)
    at java.lang.Thread.run (Thread.java:745)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.464 s
[INFO] Finished at: 2019-12-09T17:34:25-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project Jprogdyn: An exception occured while executing the Java class. element not found for symbol Br -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
***

When I use molecules without halogen atoms, I get the NMR corrections well. Have you encountered this problem before?

Thank you so much!
Juan

**Comment by ekwan** [comment]
Hi Juan,

Thanks for your message.  Jprogdyn only understand the elements that are hard-coded into `Element.java`:

```
    /** Hydrogen. */
    HYDROGEN("H", 1),

    /** Carbon. */
    CARBON  ("C", 6),
```

You can easily add any elements of interest to this list.  Could you please try this and let me know if that works?

(As you know special methods are needed for nuclei bearing halogen atoms, so it will be interesting to see how good the results are for such cases.)

Thanks,
-Eugene

**Comment by jvalegre** [comment]
It worked, thanks for your help! Regarding the accuracy of H shift calculations in molecules with F, Cl and Br, I'll do a little bit of benchmarking with molecules bearing different types of halogens to check that everything goes well with the corrections.

Best,
Juan

**Comment by ekwan** [comment]
Hi Juan,

It would be really interesting to see whether the use of "first principles" for both dynamic and relativistic corrections would lead to better prediction of carbons bearing halogens, which are generally poorly predicted.  Please feel free to reach out anytime if you need anything else.

Best,
-Eugene

**Comment by jvalegre** [comment]
Hi Eugene,

Since I'll do a benchmarking study to check for 1H NMR corrections it'd be quite straightforward to check also for 13C shifts - I'll send you an email when I know more.

Thanks again!
Juan
